name: Analysis

on:
    workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:
    check_app:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-flutter
            - name: Check with dart format
              run: |
                  dart format --set-exit-if-changed lib/components lib/screens lib/access_token.dart lib/config.dart \
                  lib/constants.dart  lib/graphql_client.dart lib/layouts.dart lib/main.dart lib/oauth_client.dart \
                  lib/router.dart test/a
            - name: Check with flutter analyze
              run: flutter analyze
