name: CD

on:
    push:
        tags:
            - "v*"

    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build_android_aab:
        environment:
            name: android-app
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-flutter
            - name: Decode keystore file
              run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
            - name: Create key.properties
              run: |
                  echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
                  echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
                  echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
                  echo "storeFile=keystore.jks" >> android/key.properties
            - run: |
                  flutter build appbundle --release --obfuscate --split-debug-info=./build/symbols \
                  --dart-define IDENTITY_CLIENT_ID="${{ vars.IDENTITY_CLIENT_ID }}"
            - run: |
                  mkdir artifact
                  mv build/app/outputs/bundle/release/app-release.aab artifact/trailers-app-${{ github.ref_name }}.aab
                  mv build/app/outputs/mapping/release/mapping.txt artifact/mapping.txt
                  mkdir -p artifact/symbols/arm64-v8a
                  mkdir artifact/symbols/armeabi-v7a
                  mkdir artifact/symbols/x86_64
                  cp build/symbols/app.android-arm64.symbols artifact/symbols/arm64-v8a/libapp.so.sym
                  cp build/symbols/app.android-arm.symbols artifact/symbols/armeabi-v7a/libapp.so.sym
                  cp build/symbols/app.android-x64.symbols artifact/symbols/x86_64/libapp.so.sym
            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: trailers_android_aab_build
                  path: ./artifact/
                  retention-days: 1
                  overwrite: true

    build_android_apk:
        environment:
            name: android-app
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-flutter
            - name: Decode keystore file
              run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
            - name: Create key.properties
              run: |
                  echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
                  echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
                  echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
                  echo "storeFile=keystore.jks" >> android/key.properties
            - run: |
                  flutter build apk --release \
                  --dart-define IDENTITY_CLIENT_ID="${{ vars.IDENTITY_CLIENT_ID }}"
            - name: Rename package
              run: mv ./build/app/outputs/flutter-apk/app-release.apk ./trailers-app-${{ github.ref_name }}.apk
            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: trailers_android_apk_build
                  path: ./trailers-app-${{ github.ref_name }}.apk
                  retention-days: 1
                  overwrite: true

    build_web:
        environment:
            name: web-app
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: actions/configure-pages@v6
            - uses: ./.github/actions/setup-flutter
            - run: |
                  flutter build web --release \
                  --dart-define IDENTITY_CLIENT_ID="${{ vars.IDENTITY_CLIENT_ID }}"
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./build/web

    release:
        needs: build_android_apk
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_android_apk_build
                  path: artifact/
            - uses: softprops/action-gh-release@v2
              with:
                  files: artifact/trailers-app-${{ github.ref_name }}.apk
                  generate_release_notes: true
                  prerelease: ${{ contains(github.ref_name, '-alpha') }}

    publish_android_aab:
        needs: build_android_aab
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - uses: actions/download-artifact@v8
              with:
                  name: trailers_android_aab_build
                  path: artifact/
            - uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
                  packageName: app.mango3.trailers
                  releaseFiles: artifact/trailers-app-${{ github.ref_name }}.aab
                  mappingFile: artifact/mapping.txt
                  debugSymbols: artifact/symbols
                  status: ${{ vars.GOOGLE_PLAY_STATUS }}
                  track: ${{ vars.GOOGLE_PLAY_TRACK }}
                  releaseName: ${{ github.ref_name }}

    deploy_web:
        needs: build_web
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-24.04
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
